version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: popcat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d popcat"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./backend
    environment:
      PORT: 8787
      DATABASE_URL: postgresql://postgres:postgres@db:5432/popcat
      ALLOWED_ORIGIN: http://localhost:5173
      RATE_WINDOW: 30
      RATE_MAX: 800
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8787:8787"
    restart: unless-stopped

volumes:
  pgdata:
