version: '3.8'
services:
  redis:
    image: redis:7-alpine
    command: ["--save","","--appendonly","no"]
    ports: ["6379:6379"]
  backend:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379
    ports: ["8080:8080"]
    depends_on: [redis]
  frontend:
    build: ./frontend
    ports: ["5173:80"]
    depends_on: [backend]
