name: CI (PR only)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  # 1) ตรวจว่ามีไฟล์ส่วนไหนถูกแก้
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  # 2) Frontend: install + test + build (เฉพาะเมื่อแตะ frontend/**)
  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # กัน rollup native แตกบน Linux (ยังคงใช้วิธี A)
      - name: Install deps (frontend)
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm install --no-audit --no-fund

      - name: Unit tests (Vitest)
        run: npm test

      - name: Build frontend
        run: npm run build   # (ควรเป็น "vite build" ตาม package.json ล่าสุด)

  # 3) Backend: install + test + build (เฉพาะเมื่อแตะ backend/**)
  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (backend)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Unit tests (backend)
        run: |
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No backend tests, skipping..."
          fi

      - name: Build backend
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No backend build script, skipping..."
          fi
