name: CI (frontend)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test-and-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache ของ setup-node ใช้ hash จาก package-lock.json
          # แต่เราจะลบ lockfile ทิ้ง วิธี A จึงไม่ได้ cache ไว้ตรงนี้

      # วิธี A: สร้าง lock และติดตั้งบน Linux ทุกครั้ง
      - name: Install dependencies (regenerate lock on Linux)
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm install --no-audit --no-fund

      - name: Run unit tests (Vitest)
        run: npm test

      - name: Build
        run: npm run build
