name: CI (frontend)

on:
  push:
    branches: [ main ]            # ให้รันเวลา push เข้า main
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]            # ให้รันเวลา PR เข้า main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test-and-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (Vitest)
        run: npm test -- --ci --watchAll=false

      - name: Build
        run: npm run build
