name: CI to frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      # ถ้ามี lockfile -> ใช้ cache npm
      - name: Use Node.js 20 (with cache)
        if: ${{ hashFiles('frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # ถ้าไม่มี lockfile -> ใช้ Node เฉยๆ (ไม่ cache)
      - name: Use Node.js 20 (no cache)
        if: ${{ hashFiles('frontend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ติดตั้งแบบยืดหยุ่น
      - name: Install dependencies (lock-aware)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests
        run: npm test -- --ci --watchAll=false
