name: Deploy Popcat to GitHub Pages (release)

on:
  push:
    branches: [ release ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug paths
        run: |
          pwd
          ls -la
          ls -la popcat || true
          ls -la popcat/src || true
          test -f popcat/src/index.html && echo "✅ found popcat/src/index.html" || (echo "❌ index not found" && exit 1)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: popcat/src   # <= โฟลเดอร์ที่มี index.html อยู่เป็นราก

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
